### PR TITLE
Adding "Me" Panel to display self + FriendFeature

### PR DESCRIPTION
**Pull request by cjinting-nus**

### CODE REVIEW

**Comment by cjinting-nus** [comment]
Will be adding tests in a separate PR

**Comment by cjinting-nus** [comment]
But for now #56 can be merged and it works

**Comment by nianfei97** [comment]
Is there no feasible way to fix the system tests?

**Comment by bennchong** [comment]
> Is there no feasible way to fix the system tests?
Oh yes why are we removing system test in branch 206e73f? @cjinting-nus

**Comment by bennchong** [comment]
Ok I'll look into it. Can they be instantiated with stubs first?

**Comment by cjinting-nus** [comment]
I have a separate branch now, working on seeing if the systemTests can be amended

**Pull request closed without merging**
