### PR TITLE
Increased minimum size of mainwindow to 1400 x 800

### PR DESCRIPTION
**Pull request by alexiscatnip**
Now the Mainwindow will always fully display the timetable panel.

### CODE REVIEW

**Comment by nianfei97** [comment]
Looks like something horribly wrong happens when you try to increase the size of the app...

**Comment by cjinting-nus** [comment]
Seems like it wasn't a simple fix..

**Comment by nianfei97** [comment]
k found the problem:

image

Add this line in `build.gradle`

**Comment by cjinting-nus** [comment]
Nice catch, @nianfei97

**Comment by nianfei97** [comment]
I'll just close this and remake the PR since I'm pretty much done changing things on my branch

**Pull request closed without merging**
