### PR TITLE
Free command

### PR DESCRIPTION
**Pull request by nianfei97**
- [x] `free` backend and tests
- [x] `free` frontend and tests (`execute` tests deferred until #56 is merged)
- [x] `free` graphics (make it look different from normal timetables)
- [x] Remove `index` from `addtime` and `deletetime`

Note:
Integration with `select` command is scrapped due to time constraints. To use `free`, users must input `free [INDICES]`.

### CODE REVIEW

**Comment by nianfei97** [comment]
Closes #26

**Comment by nianfei97** [comment]
Back to ongoing while I integrate with the new `Me` panel

**Comment by nianfei97** [comment]
Ready to merge

**Comment by bennchong** [comment]
Looks good

**Pull request merged**
