### PR TITLE
Registration UI 

### PR DESCRIPTION
**Pull request by bennchong**
RegistrationWindow UI logic done (Showing UI box, closing and opening login window)

### CODE REVIEW

**Comment by bennchong** [comment]
@cjinting-nus Ok pulling into this separate branch has issues, so i did a manual fix. On my master branch I pulled already. Merge this if it passes the test

**Comment by bennchong** [comment]
@cjinting-nus @nianfei97 @alexiscatnip could this be merged?

**Comment by nianfei97** [comment]
I think it'd be better if the stuff from #31 was fixed and merged first, since this has stuff from #31 too.

**Comment by nianfei97** [comment]
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

Doing this to force the thing to recheck...

**Comment by nianfei97** [comment]
Looks like I broke this permenantly... My bad.

Can remake PR?

**Pull request closed without merging**
